### PR TITLE
Update contact Twitter to @ethdotorg

### PR DESCRIPTION
**Pull request by samajammin**
### Description of the Change
Update Twitter link to Etheruem.org's handle:
https://twitter.com/ethdotorg

### Benefits
More relevant for users

### Possible Drawbacks
None as far as I know

### Verification Process
Tried so run & test locally but hit issues:
https://github.com/SuperblocksHQ/ethereum-studio/issues/25

### CODE REVIEW

**Comment by jjmstark** [comment]
I'm not actually sure about this - is the @ethdotorg twitter more relevant for the user in this case?

@ethereum is the "general interest" Ethereum twitter account, which shares content ranging from developer resources to major ecosystem updates to product launches. It tweets often and has a very large number of followers.

@ethdotorg exists *only* to share updates about the website ethereum.org, including new translations, new features, interesting PRs, etc. Goal is to make community more aware of what's available on the site, drive traffic, and recruit contributors.

I think there's a case to be made that @ethereum is a better "first contact" twitter account for a new developer who is using the Studio.

**Comment by samajammin** [comment]
Good points @jjmstark - I guess I was thinking about it from a product feedback & user support point-of-view. I'm fine with keeping the main Ethereum account.

**Comment by bashlund** [comment]
@samajammin is this PR then not relevant anymore? :) We keep the Twitter handle as `@Ethereum` ?

**Comment by samajammin** [comment]
Correct, closing this out.

**Pull request closed without merging**
