### PR TITLE
Moved template README images to use the ones from the static folder

### LINKED ISSUE #183: Broken images in project template READMEs
## Environment/Browser
Simply tell which browser and version of it you are using
All

## Description
Concise and descriptive message explaining what the issue is

The configure/compile/deploy images referenced in the README are broken:

Image 2020-01-21 at 2 46 27 PM

The images also appear in the user's app directory. I don't feel there's any need for this:

Image 2020-01-21 at 2 48 47 PM

## Steps to reproduce
1. View any README preview

## Expected result
Images should load

## Actual result
Images don't load

## Reproducible
100%

### PR DESCRIPTION
**Pull request by javier-tarazaga**
### Description of the Change

Change from where images from the README file are being loaded. Atm they are broken and should be served from the `static` site's folder. 

### Github Issues

This fixes #183

### CODE REVIEW

**Comment by samajammin** [comment]
Thanks @javier-tarazaga! Anything I can do to review/test this & get it merged?

**Comment by javier-tarazaga** [comment]
@samajammin if you start the project locally and see it working

**Comment by ChrisChinchilla** [comment]
Odd, when did that change 🤔

**Comment by samajammin** [comment]
I'm having trouble getting my local env running (I'll create an issue if this persists) - @Spejbl could you please quickly review this & merge if it's working? Thanks!

**Comment by samajammin** [comment]
Fixed my local env issues but @javier-tarazaga when I started the project locally (via `npm start`), the READMES in the UI are out of date (they still link to /images/ dir & as a result are still broken):

Image 2020-02-05 at 10 38 55 AM

 Is there a build step I'm missing to update the README files in the UI? Running `npm build` yields an error:
```
$ npm build
npm WARN build `npm build` called with no arguments. Did you mean to `npm run-script build`?
```

**Comment by javier-tarazaga** [comment]
@samajammin sounds like a good idea in fact. We should not have to explain the UX of the tool in the readmes of the templates

**Pull request merged**
